server:
  port: 8030
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/miaozhenqing/scloud
          searchPaths: config-server/src/main/resources/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
