server:
  port: 8012
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
# 测试【配置客户端】时，将eureka的信息移动到bootstrap.yml中
spring:
  application:
    name: product-view-service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  zipkin:
    base-url: http://localhost:9411

#开启断路器
#feign.hystrix.enabled: true
#版本问题，改成这个配置
feign:
  circuitbreaker:
    enabled: true

#这样才能访问 /actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
