server:
  port: 8030
spring:
  application:
    name: config-server
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/miaozhenqing/scloud
          default-label: main
          search-paths: config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
